import numpy as np  
import pandas as pd
pd.set_option('html', False)
import pickle 
import enrollments
import seq_readout

#Reads in enrollment data and merges with SEQ data
#Read CSV file generated by SIS (Note: SIS file is missing the last three columns, which must be added manually) 
#Missing data is filling in with "NO DATA"
#By doing .stack() it organises the data in to individual enrollments rather than the individual feilds of Name etc
a = pd.read_csv('FullEnrollmentReport_2016_T1.csv')
a = a.fillna(value='NO DATA')
a = a.stack()


#Create array of enrollments
sa = []
for i in range(0,a.count()/a[0].count()):
    x = Enrollment(a[i]['Student Name'],a[i]['Email'],a[i]['School'],a[i]['Grade'],a[i]['Course'],a[i]['Class Code'],a[i]['Teacher'],a[i]['Session'],a[i]['Year'],'Dummy',1.00)
    sa.append(x)
print('\n' + '\n' + str(a.count()/a[0].count()) + ' enrollments in file'+ '\n' + str(len(sa))+ ' enrollments loaded')   

#Reads SEQ data file provided by Matt of individual SEQ responses
df = pd.read_csv('Copy of SEQ DB.csv').stack()

#Create array of SEQ objects (of individual responses)
seqs = []
for i in range(0,df.count()/df[0].count()):
    x = SEQ(df[i]['Grade'],df[i]['Course'],df[i]['Class'],df[i]['Teacher'],df[i]['Term'],df[i]['Year'],df[i]['Rating'])
    seqs.append(x)
print('\n' + '\n' + str(df.count()/df[0].count()) + ' SEQs in file'+ '\n' + str(len(seqs))+ ' SEQs loaded')   

#Combine the SEQ data with the enrollment data. 
for i in sa:
    i.seq = SEQcalc(seqs, seqenr(i))

yy = enr2lst(sa)

errors = enr2lst(select(sa,['seq',-1]))
    
    
#read/write into file commands    
#with open('testfile','wb') as f:
#    pickle.dump(ss,f)
#
#with open('testfile','rb') as g:
#    rf = pickle.load(g)
